gui:
  language: "en"
  nerdFontsVersion: "3"
  scrollHeight: 10
  showNumstatInFilesView: true
git:
  overrideGpg: true
  pagers:
    - colorArg: always
      pager: "delta --dark --paging=never --commit-style box --true-color always"
promptToReturnFromSubprocess: false
disableStartupPopups: true
