[tools]
# Complex
"aqua:Myriad-Dreamin/tinymist" = "latest"
"aqua:apache/maven" = "latest"
"aqua:dprint/dprint" = "latest"
"aqua:duckdb/duckdb" = "latest"
"aqua:gradle/gradle" = "latest"
"aqua:pnpm/pnpm" = "latest"
"aqua:rust-lang/rust-analyzer" = "latest"
"aqua:skaji/relocatable-perl" = "latest"
"aqua:tamasfe/taplo" = "latest"
"asdf:mise-plugins/mise-gcloud" = "latest"
"asdf:mise-plugins/mise-sbt" = "latest"
"github:coursier/coursier" = "latest"
"github:skim-rs/skim" = "latest"
"vfox:mise-plugins/vfox-scala" = "latest"

# "ubi:coursier/coursier[exe=cs]" = "latest"
# "asdf:mise-plugins/mise-llvm" = "latest"

# Simple
age = "latest"
bun = "latest"
fnox = "latest"
go = "1.25"
node = "25"
python = "3.14"
sops = "latest"
zig = "0.15"

# Rust tools
"github:dathere/qsv" = "latest"

# Java
java = "temurin-25"

# Go tools
"aqua:LuaLS/lua-language-server" = "latest"
"aqua:charmbracelet/gum" = "latest"
"aqua:dominikh/go-tools/staticcheck" = "latest"
"aqua:go-swagger/go-swagger" = "latest"
"aqua:golangci/golangci-lint" = "2"
"aqua:hadolint/hadolint" = "latest"
"aqua:itchyny/gojq" = "latest"
"aqua:mr-karan/doggo" = "latest"
"aqua:muesli/duf" = "v0.9.1"
"aqua:mvdan/gofumpt" = "latest"
"aqua:mvdan/sh" = "latest"
"aqua:rest-sh/restish" = "latest"
"aqua:segmentio/golines" = "latest"
"github:Zxilly/go-size-analyzer" = "latest"
"github:a-h/templ" = "latest"
"github:dmarkham/enumer" = "latest"
"github:docker/docker-language-server" = "latest"
"github:johnkerl/miller" = "latest"
"github:marwan-at-work/mod" = "latest"
"github:oligot/go-mod-upgrade" = "latest"
"github:psampaz/go-mod-outdated" = "latest"

# Go repos
"go:github.com/golang/mock/mockgen" = "latest"
"go:github.com/icholy/gomajor" = "latest"
"go:github.com/noperator/jqfmt/cmd/jqfmt" = "latest"
"go:github.com/noperator/sol/cmd/sol" = "latest"
"go:golang.org/x/tools/cmd/stringer" = "latest"
"go:golang.org/x/tools/gopls" = "latest"

# Node tools
"npm:@biomejs/biome" = "latest"
"npm:@bufbuild/buf" = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:@tailwindcss/language-server" = "latest"
"npm:mcp-hub" = "latest"
"npm:prettier" = "latest"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"

# Python tools
"pipx:black" = "latest"
"pipx:codespell" = "latest"
"pipx:httpie" = "latest"
"pipx:ipython" = "latest"
"pipx:isort" = "latest"
"pipx:pyright" = "latest"
"pipx:ruff" = "latest"

[settings]
disable_hints = ["*"]
experimental = true

http_timeout = "5m"

npm.package_manager = "bun"
pipx.uvx = true
python.uv_venv_auto = "create|source"

env_cache = true

[plugins]
fnox-env = "jdx/mise-env-fnox"
