[colors.primary]
background = '#0e131a'
foreground = '#fefefe'

[colors.selection]
text = '#fefefe'
background = '#23262e'

[colors.cursor]
text = '#0e131a'
cursor = '#1a9fff'

[colors.normal]
black   = '#0e131a'
red     = '#e64c49'
green   = '#72d66e'
yellow  = '#dbcf7b'
blue    = '#3686c7'
magenta = '#3887c1'
cyan    = '#1a9fff'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e05f62'
green   = '#89e086'
yellow  = '#e8de97'
blue    = '#a2d8ff'
magenta = '#33839d'
cyan    = '#567aaa'
white   = '#ffffff'
